yii2/controllers/ShopController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\Products;
use app\models\Orders;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\base\Security;


class ShopController extends Controller
{
	
	/**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],

        ];
    }

    /**
     * Displays shopping app 1st page.
     *
     * @return string
     */
    public function actionIndex()
    {
		$session = Yii::$app->Session;
		/*Clear session if back to index page*/
		/*If got flash error, keep in $hasFlash*/
		$hasFlash = ($session->getFlash('error')) ? $hasFlash = $session->getFlash('error') : array();
		/*Clear all session data*/
		$session->destroy();
		/*If $hasFlash not empty, setFlash again*/
		if (!empty($hasFlash))	{	$session->setFlash('error',$hasFlash);	}

		/*If form submitted from modal screen, save the product_id  and quantity in session*/
		if (Yii::$app->request->post())
		{
			$orders = new Orders();
			if ($orders->load(Yii::$app->request->post()) && $orders->validate(['product_id','quantity']))
			{
				$session->set('product_id',$orders->product_id);
				$session->set('quantity',$orders->quantity);
				/*Redirect to check-out page*/
				$this->redirect(Url::toRoute(['shop/check-out']));
			}
			
			
		}
		/*Otherwise show the default product listing page*/
		$this->layout = 'shop';
		$pageTitle = 'Product List - Simple Shopping App';
		$all_products = Products::find()->all();
        return $this->render('index',['title'=>$pageTitle, 'products'=>$all_products]);
    }
	
	/**
	 * Display the selected product in the modal window
	**/
	public function actionShowProduct($id = null)
	{

		$productInfo = Products::findOne($id);
		
		if (isset($productInfo) && Yii::$app->request->isAjax)	
		{
			
			$model = new Orders();
			$model->product_id = $id;
			return $this->renderAjax('product_form',['model'=>$model]);
			
		}	else	{
			$session = Yii::$app->Session;
			$session->setFlash('error', "Please follow the proper flow of the shopping app!");
			$this->goHome();
			
		}
		
	}
	
	/*For Testing*/
	public function actionTest()
	{
		$session = Yii::$app->Session;
		return $session->get('product_id').' '.$session->get('quantity');
		//$this->renderAjax('test');
	}
	
	/**
	 * Check Out Screen to display selected Product and Quantity
	**/
	public function actionCheckOut()
	{
		$session = Yii::$app->Session;
		/*Check session, if no product_id and quantity, redirect back to index page*/
		
		if ($session->get('product_id') !== null && $session->get('quantity') !==null)
		{
			$model = new Orders();
			$model->product_id = $session->get('product_id');
			$model->quantity = $session->get('quantity');
			$model->delivery_country = $session->get('delivery_country');
			$model->discount_code = $session->get('discount_code');
			
			/*Get Total Price*/
			
			$getTotalPrice = ($this->GetTotalPrice()) ? $this->GetTotalPrice() : $this->redirect(Url::toRoute('/'));;
			$model->priceInfo = $getTotalPrice;
			$model->total_price = $getTotalPrice['Total'];
			$model->unit_price = $model->product->selling_price;

			/*If submitted from check-out page. and validated passed*/
			
			if ($model->load(Yii::$app->request->post()) && $model->validate())
			{
				//$session->setFlash('error', "Saved");
				//$model->save();
				/*
					suppose to save the order into database, then redirect to summary page
					but i will just store it into session for this Testing purpose
				*/
				/*Not going to get order from database, will get from session this time*/
				/*Generate a random order number for this testing, suppose to get from database*/
				$myordernumber = $this->generateRandomOrderNumber(6);
					
				$dataToBeSaved = array(
					'orderNumber' => 'ORD'.$myordernumber,
					'product_id' => $model->product_id,
					'product_idName' => $model->product->product_name,
					'brand' => $model->product->brand,
					'quantity' => $model->quantity,
					'delivery_country' => $model->delivery_country,
					'delivery_countryName' => $model->countryName,
					'discount_code' => $model->discount_code,
					'unit_price' => $model->unit_price,
					'total_price' => $model->total_price,
					'priceInfo' => $model->priceInfo
				
				);
				
				$session->set('FinalSummary',$dataToBeSaved);
				$this->redirect(Url::toRoute('shop/summary'));
				
			}	

			
			$this->layout = 'shop';
			$pageTitle = 'Check Out - Simple Shopping App';
			return $this->render('check_out',['title'=>$pageTitle, 'model' => $model]);
			
		}	else	{
			$session->setFlash('error', "Please follow the proper flow of the shopping app!");
			$this->goHome();
		}
		

	}
	
	private function generateRandomOrderNumber($length)
	{
		$rNumber = '';
		for ($i = 0; $i<$length; $i++)
		{
			$rNumber .=  (rand(0,9));
		}
		return $rNumber;
	} 
	
	/**
	 * Check Out Screen to display selected Product and Quantity
	**/
	public function actionSummary()
	{
		$session = Yii::$app->Session;
		
		/*If session cannot be found, redirect to home with error*/
		if($session->get('FinalSummary') !== null)
		{
			$this->layout = 'shop';
			$pageTitle = 'Summary - Simple Shopping App';
			
			return $this->render('summary',['title'=>$pageTitle, 'myorder'=>$session->get('FinalSummary')]);
			
		} else	{
			$session->setFlash('error', "Please follow the proper flow of the shopping app!");
			$this->goHome();
		}
	}
	/*
	 * Return total price
	*/
	private function GetTotalPrice()
	{
		$session = Yii::$app->Session;

		$s_deliver_country = $session->get('delivery_country');
		$s_discount_code = $session->get('discount_code');
		
		/*Check session, if no product_id and quantity, redirect back to index page*/
		if ($session->get('product_id') !== null && $session->get('quantity') !== null)
		{
			/*assign session value into model*/
			$orders = new Orders();
			$orders->product_id = $session->get('product_id');
			$orders->quantity = $session->get('quantity');
			$orders->delivery_country = $session->get('delivery_country');
			$orders->discount_code = $session->get('discount_code');
			
			
			$unitPrice = $orders->product->selling_price;
			$quantity = $orders->quantity;
			/*Calculate the total Product rice*/
			$price['ItemOnly'] = $unitPrice * $quantity;
			
			$price['ShipFee'] = 0;
			
			/*Calculate the Shipping Fee*/
			switch ( $orders->countryName)
			{
				case 'Malaysia':
					$price['ShipFee'] = ($quantity >= 2 || $price['ItemOnly'] > 150) ? 0 : 10;
					break;
					
				case 'Singapore':
					$price['ShipFee'] = ($price['ItemOnly'] > 300) ? 0 : 20;
					break;
				
				case 'Brunei':
					$price['ShipFee'] = ($price['ItemOnly'] > 300) ? 0 : 25;
					break;
				default:
				case '':
					$price['ShipFee'] = 0;
					break;
			}
			
			/*Calculate the Discount*/
			$price['Discount'] = 0;
			if ($session->get('discount_code'))	{
				switch ($session->get('discount_code'))
				{
					case 'GIVEME15':
						//$price['Discount'] =  15 ;
						/*Validate 1 more time in case user submit improper*/
						$price['Discount'] = ($price['ItemOnly'] >= 100) ? 15 : 0;
						break;
					
					case 'OFF5PC':
						//$price['Discount'] = $price['ItemOnly']*(5/100) ;
						/*Validate 1 more time in case user submit improper*/
						$price['Discount'] = ($quantity >= 2)? $price['ItemOnly']*(5/100) : 0 ;
						break;
					default:
					case '':
						$price['Discount'] = 0;
						break;
				}
			}
			
			/*Calculate Final Total*/
			$price['Total'] = $price['ItemOnly'] - $price['Discount'] + $price['ShipFee'];
			
			return $price;
		
		}	else	{
			
			return false;
			
		}
	}
	
	/*
	 * Get Price via Ajax
	*/
	public function actionAjaxGetTotalPrice()
	{
		if (Yii::$app->request->isAjax)
		{
		Yii::$app->response->format = Response::FORMAT_JSON;
		
		$session = Yii::$app->Session;
		$orders = new Orders;
		$orders->product_id = $session->get('product_id');
		$orders->quantity = $session->get('quantity');
		
		$orders->load(Yii::$app->request->post());
		$orders->validate();
		
		/*Save the latest delivery_country into session if no error*/
		if (empty($orders->getErrors('delivery_country')))
		{
			$session->set('delivery_country',$orders->delivery_country);
		}
		
		/*Save the latest discount_code into session if no error*/
		if (empty($orders->getErrors('discount_code')))
		{
			$session->set('discount_code',$orders->discount_code);
		}
		
		
		$price = $this->GetTotalPrice();

		/**Build Price from GetTotalPrice and formate as currencyt**/
		foreach ($price as $key=>$value)
		{
			$ajaxPrice[$key] = Html::encode(\Yii::$app->formatter->asCurrency($value));
		}
		
		$response['Price'] = $ajaxPrice;
		
		/**Build Error Message from validated Error**/
		foreach ($orders->getErrors() as $attribute => $errors) {
            $Error[yii\helpers\Html::getInputId($orders, $attribute)] = $errors;
        }
		
		$response['Error'] = $Error;
		
		
		return $response;
		}	else	{
			$session->setFlash('error', "Please follow the proper flow of the shopping app!");
			$this->goHome();
		}
		
	}
}

yii2/views/shop/check_out.php
<?php


use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;
$formatter = \Yii::$app->formatter;
$this->title = $title;
/*Use customized ajaxValidate JS*/
$urlTotalByAjax = Url::toRoute('shop/ajax-get-total-price');
$this->registerJs( <<< EOT_JS


$("#orders-delivery_country").on('change.yii',validateAjax);
$("#orders-discount_code").on('blur',validateAjax);

$('#check-out-form').on('beforeSubmit', function (e) {
	if ($('#orders-discount_code').val() === '')
	{
		console.log(validateAjax);
		if (!confirm("Without Discount Code?")) {
			return false;
		}
		
	}


    return true;
});



function validateAjax()
{

	var country = $('#orders-delivery_country').val();
	var discount_code = $('#orders-discount_code').val();
	var param = {
		'Orders' : {
			'delivery_country' : country,
			'discount_code' : discount_code
			}
		};
	

	$.post(
		'{$urlTotalByAjax}',
		param,
		function(data) {
			//console.log(data);
			 			
			var priceInfo = data.Price;
			$('td#priceInfo-discount').html(priceInfo.Discount).addClass('w3-animate-left').delay(1000).queue(function(){
				$(this).removeClass("w3-animate-left").dequeue();
			});
			$('td#priceInfo-shipfee').html(priceInfo.ShipFee).addClass('w3-animate-left').delay(1000).queue(function(){
				$(this).removeClass("w3-animate-left").dequeue();
			});;
			$('td#priceInfo-total').html(priceInfo.Total).addClass('w3-animate-left').delay(1000).queue(function(){
				$(this).removeClass("w3-animate-left").dequeue();
			});;
			
			if(data.Error) {
				$('#check-out-form').yiiActiveForm('updateMessages', data.Error, true);
            }

			
		}
	)

}

EOT_JS

);

?>
<div class="w3-container">
	<div class="w3-container"><h3>Check Out</h3></div>
	<div class="w3-row w3-small w3-section">
		<div class="w3-third">
			<div class="w3-large w3-padding w3-theme-d3">Product Info</div>
			<div class="w3-circle w3-green w3-display-container" style="width:100px;height:100px;margin: 16px auto">
				<span class="w3-display-middle">IMG</span>
			</div>
			<div class="w3-panel w3-center"><p><strong><?=Html::encode($model->product->product_name)?></strong> (<?=$model->product->brand?>)</p></div>
		</div>
		<div class="w3-third">
			<div class="w3-large w3-padding w3-theme-d3">Price Info</div>
			<div class="w3-panel">
				<table class="w3-table" style="font-weight:bold">
				<tr>
				  <td><strong>Price</strong></td><td class="w3-right-align"><span class="w3-text-grey w3-tiny" style="text-decoration:line-through ">(<?=Html::encode($formatter->asCurrency($model->product->retail_price))?>)</span> <?=Html::encode($formatter->asCurrency($model->product->selling_price))?></td>
				</tr>
				<tr>
				  <td><strong>Quantity</strong></td><td class="w3-right-align"><?=Html::encode($model->quantity)?></td>
				</tr>
				<tr>
				  <td><strong>Subtotal</strong></td><td class="w3-right-align"><?=Html::encode($formatter->asCurrency($model->priceInfo['ItemOnly']))?></td>
				</tr>
				<tr>
				  <td><strong>Discount</strong></td><td id="priceInfo-discount" class="w3-right-align">- <?=Html::encode($formatter->asCurrency($model->priceInfo['Discount']))?></td>
				</tr>
				<tr>
				  <td><strong>Shipping Fee</strong></td><td id="priceInfo-shipfee" class="w3-right-align"><?=Html::encode($formatter->asCurrency($model->priceInfo['ShipFee']))?></td>
				</tr>
				<tr>
				  <td><strong>Total</strong></td><td id="priceInfo-total" class="w3-right-align"><?=Html::encode($formatter->asCurrency($model->priceInfo['Total']))?></td>
				</tr>
				</table>
			</div>
		</div>
		<?php 		
			$form = ActiveForm::begin(
				[
					'id' => 'check-out-form',
					'enableClientValidation' => true,
					'validateOnChange' => true,
					'validateOnSubmit' => true,
					'action' => Url::toRoute('shop/check-out'),
					'options' => ['class'=>'w3-third'],
					'errorCssClass' => 'w3-text-red'
				]
			);
		?>
		<div class="w3-large w3-padding w3-theme-d3">Extra Info</div>
		<div class="w3-panel">
			<?=$form->field($model,'id')->hiddenInput()->label(false)?>
			<?=$form->field($model,'product_id')->hiddenInput()->label(false)?>
			<?=$form->field($model,'quantity')->hiddenInput()->label(false)?>
			<?=$form->field($model,'discount_code')->textInput(['class'=>'w3-input w3-border','placeholder' => 'OFF5PC / GIVEME15','autofocus' => true])?>
			<?=$form->field($model,'delivery_country')->dropDownList($model->countryMatrix,['prompt'=>'-Select a country-','class'=>'w3-select w3-border'])?>

			<?=Html::a('Cancel',Url::toRoute('/'),['class'=>'w3-btn w3-theme-action'])?>
			<?=Html::submitButton('Check Out',['class'=>'w3-btn w3-theme-action w3-right'])?>

			<?php ActiveForm::end();?>
		</div>
	</div>
</div>

yii2/views/shop/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

yii2/views/shop/index.php
<?php

/* @var $this yii\web\View */
/*
	@var model Products model
	@var products Products::getAll
	@var title PageTitle
*/
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
$this->title = $title;


?>
<div class="w3-container">
	<div class="w3-panel"><h3>Product Listing</h3></div>
	<?php if (isset($products)) {?>
    <div class="w3-section">
		<div class="w3-row">
       <?php
			foreach($products as $product){
			   echo $this->render('product_card',['product'=>$product]);
		   }
	   ?>
	   </div>
    </div>
	<?=$this->render('modal_window',['modalId'=>'jPurchase','modalHeader'=>'Purchase Form'])?>
	
	<?php }	else { ?>
	<div>
		<p>Nothing to show.</p>
	</div>
	<?php } ?>
</div>

yii2/views/shop/modal_window.php
<?php
/**
*Modal template for purchase form
**/
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
?>
<div id="<?=Html::encode($modalId)?>" class="w3-modal">
  <div class="w3-modal-content w3-animate-zoom w3-card-4">
	
    <header class="w3-container w3-theme-d5"> 
      <span onclick="closeMe('jPurchase')" class="w3-button w3-display-topright">&times;</span>
      <h2><?=Html::encode($modalHeader)?></h2>
    </header>
    <div id="modal-content" class="w3-container">
		<p><i class="fa fa-spinner w3-spin" style="font-size:48px"></i></p>
    </div>

    <footer class="w3-container">
	</footer>
  </div>
</div>

yii2/views/shop/product_card.php
<?php
/**
* Display Product Card
**/
use yii\helpers\Html;
use yii\helpers\Url;
//use yii\bootstrap\ActiveForm;
$formatter = \Yii::$app->formatter;

?>

<div class="w3-third w3-padding">
	<div class="w3-hover-shadow w3-center w3-theme-l5" style="min-height:180px">
		<header class="w3-theme-d2">
			<span class="w3-padding w3-large"><?=$product['brand']?></span>
		</header>
		<div class="w3-row-padding w3-center">
			<div class="w3-third w3-mobile">
				<div class="w3-circle w3-green w3-display-container w3-center" style="width:100px;height:100px;margin:16px auto">
					<span class="w3-display-middle">IMG</span>
				</div>
			</div>
			<div class="w3-twothird w3-mobile">
				<div class="w3-container w3-small w3-margin">
					<div class="w3-row">
						<h5><?=$product['product_name']?></h5>
					</div>
					<div class="w3-row">
						<span class="w3-text-grey" style="text-decoration:line-through"><?=$formatter->asCurrency($product['retail_price'])?></span><br/><span><strong><?=$formatter->asCurrency($product['selling_price'])?></strong></span>
					</div>
					<div class="w3-row">
						<?=HTML::button('Buy Now',[
							'class'=>'w3-btn w3-theme-action w3-margin-top',
							'onclick'=>'openModal(\'jPurchase\',\''.$product['id'].'\',\''.Url::toRoute('shop/show-product/'.$product['id']).'\')'])?>
					</div>	
				</div>
			</div>
		</div>
	</div>
</div>

yii2/views/shop/product_form.php
<?php
/*
 * Display 1 single product purchase form
 * @var $model = Selected Product
*/

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\helpers\Url;
$formatter = \Yii::$app->formatter;
$dropDownValues = range(1,10);
foreach($dropDownValues as $value)	{
	$dropDownData[$value] = $value;
};
?>

<?php 		
	$form = ActiveForm::begin(
		[
			'id' => 'product-form',
			'action' => Url::toRoute('shop/index')
		]
	);
	
?>
<?=$form->field($model,'id')->hiddenInput()->label(false)?>
<?=$form->field($model,'product_id')->hiddenInput()->label(false)?>
<div class="w3-section">
	<p><?=Html::encode($model->product->product_name)?></p>
	<p><?=$formatter->asCurrency($model->product->selling_price)?></p>
	<div class="w3-row">
		<?=$form->field($model,'quantity')->dropDownList($dropDownData,['class'=>'w3-select w3-border'])?>
	</div>
</div>


	<p><?=Html::submitButton('Buy',['class' => 'w3-btn w3-theme-action'])?></p>



<?php ActiveForm::end();?>

yii2/views/shop/summary.php
<?php


use yii\helpers\Html;
//use yii\bootstrap\ActiveForm;
use yii\helpers\Url;
$formatter = \Yii::$app->formatter;
$this->title = $title;
//var_dump($myorder);
?>

<div class="w3-container">
	<div class="w3-container w3-border-bottom"><ul class="w3-ul">
		<li><h3>Order Number : <?=Html::encode($myorder['orderNumber'])?></h3></li></ul>
	</div>
	<div class="w3-container w3-section">
		<div class="w3-third w3-center">
			<div class="w3-circle w3-green w3-display-container" style="width:100px;height:100px;margin: 16px auto">
				<span class="w3-display-middle">IMG</span>
			</div>
			<p><strong><?=Html::encode($myorder['product_idName'])?></strong></p>
			<p><?=Html::encode($myorder['brand'])?></p>
		</div>
		<div class="w3-quarter">
			<div class="panel">
				<table class="w3-table w3-small">
					<tr>
					  <td><strong>Unit Price</strong></td><td class="w3-right-align"><?=Html::encode($formatter->asCurrency($myorder['unit_price']))?></td>
					</tr>
					<tr>
					  <td><strong>Quantity</strong></td><td class="w3-right-align"><?=Html::encode($myorder['quantity'])?></td>
					</tr>
					<tr class="w3-border-top">
					  <td><strong>Subtotal</strong></td><td class="w3-right-align"><?=Html::encode($formatter->asCurrency($myorder['priceInfo']['ItemOnly']))?></td>
					</tr>
					<tr>
					  <td><strong>Discount Code</strong></td><td class="w3-right-align"><?=Html::encode($myorder['discount_code'])?></td>
					</tr>
					<tr>
					  <td><strong>Discount</strong></td><td class="w3-right-align">- <?=Html::encode($formatter->asCurrency($myorder['priceInfo']['Discount']))?></td>
					</tr>
					<tr>
					  <td><strong>Delivery Country</strong></td><td class="w3-right-align"><?=Html::encode($myorder['delivery_countryName'])?></td>
					</tr>
					<tr>
					  <td><strong>Shipping Fee</strong></td><td class="w3-right-align"><?=Html::encode($formatter->asCurrency($myorder['priceInfo']['ShipFee']))?></td>
					</tr>
					<tr class="w3-border-top">
					  <td><strong>Total</strong></td><td class="w3-right-align"><?=Html::encode($formatter->asCurrency($myorder['priceInfo']['Total']))?></td>
					</tr>
				</table>
			</div>
			<p><?=Html::a('Finish',Url::toRoute('/'),['class'=>'w3-btn w3-theme-action w3-right'])?></p
		</div>
	
	</div>
</div>